name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build the docs
        run: pnpm run docs:build

      - name: Setup Git user
        run: |
          git config --global user.name "GuYun-D"
          git config --global user.email "1946306647@qq.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/vitepress/dist
          publish_branch: gh-pages
          user_name: 'GuYun-D'
          user_email: '1946306647@qq.com'
