name: Run test when push

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Install compatible pnpm
        run: npm install -g pnpm@7

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
